#!/usr/bin/env python3
"""
Generates the accessors model definitions use to reach vanilla fields, whose names are obfuscated
in production:

  * goblinbob/mobends/core/vanilla/VanillaModelParts.java   every ModelRenderer / ModelRenderer[]
    field of every vanilla model,
  * goblinbob/mobends/core/vanilla/VanillaEntityFields.java every numeric field of Entity,
    EntityLivingBase and the living entities,
  * the generated section of META-INF/accesstransformer.cfg, making the non-public ones readable.

The accessors read the fields directly, so the compiler checks every name and reobfuscation renames
them for production; no SRG name is looked up at runtime. Fields added by mods are not obfuscated
and are found by reflection instead (see DefinedFields).

Reads the SRG-named Forge jar (the access flags before this mod's access transformer) and the
SRG-to-MCP mappings from ForgeGradle's cache in build/fg_cache, so run the Gradle setup first.
Usage: gen_vanilla_fields.py [repo root]   (or `gradle generateVanillaFields`)
"""
import glob
import os
import struct
import sys
import zipfile

ROOT = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..'))
JAVA = os.path.join(ROOT, 'src', 'main', 'java', 'goblinbob', 'mobends', 'core', 'vanilla')
AT = os.path.join(ROOT, 'src', 'main', 'resources', 'META-INF', 'accesstransformer.cfg')
AT_BEGIN = '# --- generated by tools/gen_vanilla_fields.py, do not edit below ---'

MODEL_BASE = 'net/minecraft/client/model/ModelBase'
MODEL_RENDERER = 'Lnet/minecraft/client/model/ModelRenderer;'
ENTITY = 'net/minecraft/entity/Entity'
LIVING = 'net/minecraft/entity/EntityLivingBase'
NUMERIC = {'F', 'D', 'I', 'J', 'S', 'B'}

ACC_PUBLIC, ACC_STATIC, ACC_SYNTHETIC = 0x0001, 0x0008, 0x1000


def gradle_properties():
    props = {}
    with open(os.path.join(ROOT, 'gradle.properties')) as f:
        for line in f:
            if '=' in line and not line.lstrip().startswith('#'):
                key, value = line.split('=', 1)
                props[key.strip()] = value.strip()
    return props


def inputs():
    p = gradle_properties()
    cache = os.path.join(ROOT, 'build', 'fg_cache')
    mc, forge = p['minecraft_version'], p['forge_version']
    jar = os.path.join(cache, 'net', 'minecraftforge', 'forge', f'{mc}-{forge}', f'forge-{mc}-{forge}-srg.jar')
    mappings = glob.glob(os.path.join(cache, 'de', 'oceanlabs', 'mcp', 'mcp_config', f'{mc}-*',
                                      f"srg_to_{p['mappings_channel']}_{p['mappings_version']}.tsrg"))
    if not os.path.isfile(jar) or not mappings:
        sys.exit(f'Missing {jar} or the SRG-to-MCP mappings under {cache}: run the ForgeGradle setup (e.g. `gradle compileJava`) first.')
    return jar, mappings[0]


def read_class(data):
    """(this, super, [(access, name, descriptor)]) of a class file."""
    count = struct.unpack('>H', data[8:10])[0]
    pool = [None] * count
    p, i = 10, 1
    while i < count:
        tag = data[p]
        if tag == 1:
            length = struct.unpack('>H', data[p + 1:p + 3])[0]
            pool[i] = data[p + 3:p + 3 + length].decode('utf-8', 'replace')
            p += 3 + length
        elif tag in (7, 8, 16, 19, 20):
            pool[i] = struct.unpack('>H', data[p + 1:p + 3])[0]
            p += 3
        elif tag == 15:
            p += 4
        elif tag in (3, 4, 9, 10, 11, 12, 17, 18):
            p += 5
        elif tag in (5, 6):
            p += 9
            i += 1
        else:
            raise ValueError(f'constant pool tag {tag}')
        i += 1
    _, this, sup = struct.unpack('>HHH', data[p:p + 6])
    p += 6
    interfaces = struct.unpack('>H', data[p:p + 2])[0]
    p += 2 + 2 * interfaces
    fields = []
    count = struct.unpack('>H', data[p:p + 2])[0]
    p += 2
    for _ in range(count):
        access, name, descriptor, attributes = struct.unpack('>HHHH', data[p:p + 8])
        p += 8
        for _ in range(attributes):
            p += 6 + struct.unpack('>I', data[p + 2:p + 6])[0]
        fields.append((access, pool[name], pool[descriptor]))
    return pool[pool[this]], pool[pool[sup]] if sup else None, fields


def read_mappings(path):
    """{class: {srg field: mcp field}}"""
    fields, owner = {}, None
    with open(path) as f:
        for line in f:
            if not line.strip():
                continue
            if not line.startswith('\t'):
                owner = line.split()[0]
                fields.setdefault(owner, {})
            else:
                parts = line.split()
                if len(parts) == 2:  # methods carry a descriptor
                    fields[owner][parts[0]] = parts[1]
    return fields


def main():
    jar, mappings_path = inputs()
    mappings = read_mappings(mappings_path)
    classes = {}
    with zipfile.ZipFile(jar) as z:
        for entry in z.namelist():
            if entry.startswith('net/minecraft/') and entry.endswith('.class'):
                name, sup, fields = read_class(z.read(entry))
                classes[name] = (sup, fields)

    def extends(name, root):
        while name is not None:
            if name == root:
                return True
            name = classes[name][0] if name in classes else None
        return False

    def fields_of(owner, accept):
        found = []
        for access, srg, descriptor in classes[owner][1]:
            if access & (ACC_STATIC | ACC_SYNTHETIC) or not accept(descriptor):
                continue
            mcp = mappings.get(owner, {}).get(srg, srg)
            found.append((owner, mcp, srg, descriptor, bool(access & ACC_PUBLIC)))
        return found

    parts, numbers = [], []
    for owner in sorted(classes):
        if owner != MODEL_BASE and extends(owner, MODEL_BASE):
            parts += fields_of(owner, lambda d: d in (MODEL_RENDERER, '[' + MODEL_RENDERER))
        if owner in (ENTITY, LIVING) or extends(owner, LIVING):
            numbers += fields_of(owner, lambda d: d in NUMERIC)

    os.makedirs(JAVA, exist_ok=True)
    write_java('VanillaModelParts', 'Function<Object, Object>', 'model', parts,
               'Every model part (ModelRenderer or ModelRenderer[]) field of the vanilla models, read directly so the names are\n'
               ' * checked at compile time and reobfuscated for production.',
               ['java.util.function.Function'])
    write_java('VanillaEntityFields', 'ToDoubleFunction<Object>', 'entity', numbers,
               'Every numeric field of the vanilla living entities (and Entity), read directly so the names are checked at compile\n'
               ' * time and reobfuscated for production.',
               ['java.util.function.ToDoubleFunction'])
    write_access_transformer(parts + numbers)
    print(f'{len(parts)} model parts, {len(numbers)} entity fields, '
          f'{sum(1 for f in parts + numbers if not f[4])} made public by the access transformer')


def java_name(internal):
    return internal.replace('/', '.').replace('$', '.')


def write_java(class_name, accessor, argument, fields, doc, imports):
    lines = [
        '// Generated by tools/gen_vanilla_fields.py from the Minecraft mappings. Do not edit; regenerate instead.',
        'package goblinbob.mobends.core.vanilla;',
        '',
        *(f'import {i};' for i in imports),
        '',
        '/**',
        f' * {doc}',
        ' */',
        f'public final class {class_name}',
        '{',
        '',
        f'    private {class_name}()',
        '    {',
        '    }',
        '',
        '    /**',
        f'     * The accessor of the field {{@code name}} declared by {{@code owner}} (a binary class name), or null when',
        '     * that class declares no such field.',
        '     */',
        f'    public static {accessor} get(String owner, String name)',
        '    {',
        "        switch (owner + '#' + name)",
        '        {',
    ]
    for owner, mcp, _, _, _ in fields:
        lines.append(f'            case "{owner.replace("/", ".")}#{mcp}": return {argument[0]} -> (({java_name(owner)}) {argument[0]}).{mcp};')
    lines += [
        '            default: return null;',
        '        }',
        '    }',
        '',
        '}',
        '',
    ]
    with open(os.path.join(JAVA, class_name + '.java'), 'w') as f:
        f.write('\n'.join(lines))


def write_access_transformer(fields):
    with open(AT) as f:
        manual = f.read().split(AT_BEGIN)[0].rstrip('\n')
    already = {tuple(line.split()[1:3]) for line in manual.splitlines() if line.strip() and not line.startswith('#')}
    lines = [manual, '', AT_BEGIN]
    for owner, mcp, srg, _, public in fields:
        if not public and (owner.replace('/', '.'), srg) not in already:
            lines.append(f"public {owner.replace('/', '.')} {srg} # {mcp}")
    with open(AT, 'w') as f:
        f.write('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
